### PR TITLE
Add textures with tags to caseiro and lojista occupations

### PR DESCRIPTION
**Pull request by hkzorman**
I have made small changes on the API to support adding same texture to multiple occupations.
I tested these and all NPCs had correct textures.

### CODE REVIEW

**Comment by BrunoMine** [comment]
Thanks, add this definitions and examples in your documentation.

**Comment by BrunoMine** [comment]
Sorry, but I am working in dev branch, then I will add this commits in it.

**Comment by hkzorman** [comment]
No problem at all!

**Comment by hkzorman** [comment]
You are right, I did do a mistake... I made the change out of master branch rather than dev.

**Pull request merged**
